#!/bin/bash

pkill xautolock
xautolock -time 10 -locker "swaylock -i ~/Imágenes/wallpaper.png --effect-blur 10x3 --indicator --clock" -notify 30 -notifier "dunstify 'La pantalla se bloqueará en 30 segundos'" -killtime 5
