#!/bin/sh
down() {
  pamixer -d 5
  volume=$(pamixer --get-volume)
  if [ $volume -gt 0 ]; then
    dunstify -a "VOLUME" "Bajando a $volume%" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
    canberra-gtk-play -i dialog-error -d "error"
  fi
}

up() {
  pamixer -i 5
  volume=$(pamixer --get-volume)
  if [ $volume -lt 100 ]; then
    dunstify -a "VOLUME" "Subiendo a $volume%" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
    canberra-gtk-play -i dialog-error -d "error"
  fi
}

playpause() {
  playerctl play-pause
}

mute() {
  muted="$(pamixer --get-mute)"
  if $muted; then
    pamixer -u
    dunstify -a "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal
  else 
    pamixer -m
    dunstify -a "VOLUME" "MUTED" -i audio-volume-muted-symbolic -r 2593 -u normal
  fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
  playpause) playpause;;
esac
